#!/bin/bash

echo "Content-type: text/html"
echo ''

source /usr/share/drlm/conf/default.conf
source /etc/drlm/local.conf
source /usr/share/drlm/lib/http-functions.sh
source /usr/share/drlm/lib/client-functions.sh

CLIENT=$(echo $PATH_INFO | awk -F"/" '{print $2}')
ID=$(get_client_id_by_name $CLIENT)
IP=$(get_client_ip $ID)

if [ -f $CLI_CONF_DIR/$CLIENT.cfg ]; then
    if [ "$IP" == "$REMOTE_ADDR" ]; then
        grep -E -v "^#|=$" $CLI_CONF_DIR/$CLIENT.cfg
    else
        echo "HTTP response ?????"
    fi
else
    echo "HTTP response NOT FOUND"
fi
