#!/bin/sh
set -e

case "$1" in
    configure)
	if [ -f /var/lib/drls/client.data.save ] && mv /var/lib/drls/client.data.save /var/lib/drls/client.data
	if [ -f /var/lib/drls/backup.data.save ] && mv /var/lib/drls/backup.data.save /var/lib/drls/backup.data
	if [ -f /var/lib/drls/network.data.save ] && mv /var/lib/drls/network.data.save /var/lib/drls/network.data
	if [ -f /var/lib/drls/calendar.data.save ] && mv /var/lib/drls/calendar.data.save /var/lib/drls/calendar.data
	if [ -d var/lib/drls/.ids.save ] && mv /var/lib/drls/.ids.save /var/lib/drls/.ids
	service drls-stord start
	;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

exit 0
