#!/bin/sh
set -e

case "$1" in
    upgrade)
	#mv /var/lib/drlm/client.data.save /var/lib/drlm/client.data
	#mv /var/lib/drlm/network.data.save /var/lib/drlm/network.data
	#mv /var/lib/drlm/backup.data.save /var/lib/drlm/backup.data	
	;;

    *)
        exit 0
        ;;
esac

exit 0
