#!/bin/sh
set -e

case "$1" in
  install)
    # check host name is not localhost
    currhostname="$(hostname -s)"
    if [ "$currhostname" = "localhost" ]; then
      echo "Its important that DRLM servers have a valid hostname. Please change \"localhost\" host name. "
      exit 1
    fi
    ;;

  upgrade)
    # Check if older versions than 2.3.0 is beeing updated
    if [ -f /var/lib/drlm/drlm.sqlite.save ]; then
      [ -f /usr/sbin/drlm ] && drlm_ver="$(awk 'BEGIN { FS="=" } /VERSION=/ { print $$2 }' /usr/sbin/drlm)"
      mv /var/lib/drlm/drlm.sqlite.save /var/lib/drlm/$drlm_ver-drlm.sqlite.save
    fi

    # Check error in older versions than 2.4.5
    if [ -f /var/lib/drlm/-drlm.sqlite.save ]; then
      [ -f /usr/sbin/drlm ] && drlm_ver="$(awk 'BEGIN { FS="=" } /VERSION=/ { print $$2 }' /usr/sbin/drlm)"
      mv -- /var/lib/drlm/-drlm.sqlite.save /var/lib/drlm/$drlm_ver-drlm.sqlite.save
    fi
    
    #Stop apache2 server of older drlm versions
    systemctl is-active --quiet apache2.service && systemctl stop apache2.service
    systemctl is-enabled --quiet apache2.service && systemctl disable apache2.service

    # Check if older versions than 2.4.12
    [ -f /usr/sbin/drlm ] && drlm_ver="$(awk 'BEGIN { FS="=" } /VERSION=/ { print $$2 }' /usr/sbin/drlm) | awk -F. '{printf("%02d%02d%02d\n", $1, $2, $3)}'"
    if [[ "$drlm_ver" < "020412" ]]; then 
      echo "INFO: Since DRLM 2.4.12 the RSYNC protocol transport is secure by default!!!"
      echo "      Setting insecure transport to all current configuirations using RSYNC."
      echo "      To secure it run [ drlm instclient -c <cli_name> -C ] to each client "
      echo "      and comment out DRLM_BKP_SEC_PROT=no in all required client configurations."
      echo "      New installed clients will be secure by default!"
	  for cfg in $(find /etc/drlm/clients -type f -name "*.cfg" ! -name "*.drlm.cfg"); do 
	    PROT=$(grep -v "^#" $cfg | grep DRLM_BKP_PROT=NETFS)
	    [[ "$PROT" == "" ]] && echo "DRLM_BKP_SEC_PROT=no" >> $cfg
	  done
    fi	
    ;;

  *)
    exit 0
    ;;

esac

exit 0
