#!/bin/sh
set -e

case "$1" in
    remove)
	service drlm-stord stop
	mv /var/lib/drlm/.ids/.idcount.client /var/lib/drlm/.ids/.idcount.client.save
	mv /var/lib/drlm/.ids/.idcount.network /var/lib/drlm/.ids/.idcount.network.save
	mv /var/lib/drlm/client.data /var/lib/drlm/client.data.save
	mv /var/lib/drlm/network.data /var/lib/drlm/network.data.save
	mv /var/lib/drlm/backup.data /var/lib/drlm/backup.data.save
	#mv /var/lib/drlm/calendar.data /var/lib/drlm/calendar.data.save
        ;;

    upgrade)
	service drlm-stord stop
	mv /var/lib/drlm/.ids/.idcount.client /var/lib/drlm/.ids/.idcount.client.save
	mv /var/lib/drlm/.ids/.idcount.network /var/lib/drlm/.ids/.idcount.network.save
	mv /var/lib/drlm/client.data /var/lib/drlm/client.data.save
	mv /var/lib/drlm/network.data /var/lib/drlm/network.data.save
	mv /var/lib/drlm/backup.data /var/lib/drlm/backup.data.save
	#mv /var/lib/drlm/calendar.data /var/lib/drlm/calendar.data.save
	;;

    *)
        exit 0
        ;;
esac

exit 0
