#!/bin/sh
set -e

case "$1" in
    remove)
    if [ $(ps -p 1 -o comm=) = "systemd" ]
    then
      systemctl stop drlm-stord.service
      systemctl disable drlm-stord.service
      rm /etc/systemd/system/drlm-stord.service
      systemctl daemon-reload
    else
      service drlm-stord stop
      update-rc.d drlm-stord remove
      rm /etc/init.d/drlm-stord
    fi
	mv /var/lib/drlm/client.data /var/lib/drlm/client.data.save
	mv /var/lib/drlm/network.data /var/lib/drlm/network.data.save
	mv /var/lib/drlm/backup.data /var/lib/drlm/backup.data.save
	mv /var/lib/drlm/drlm.sqlite /var/lib/drlm/drlm.sqlite.save
	rm /etc/drlm/cert/drlm.*
    ;;

    upgrade)
    if [ $(ps -p 1 -o comm=) = "systemd" ]
    then
      systemctl stop drlm-stord.service
      systemctl disable drlm-stord.service
      rm /etc/systemd/system/drlm-stord.service
      systemctl daemon-reload
    else
      service drlm-stord stop
      update-rc.d drlm-stord remove
      rm /etc/init.d/drlm-stord
    fi
	mv /var/lib/drlm/client.data /var/lib/drlm/client.data.save
	mv /var/lib/drlm/network.data /var/lib/drlm/network.data.save
	mv /var/lib/drlm/backup.data /var/lib/drlm/backup.data.save
	mv /var/lib/drlm/drlm.sqlite /var/lib/drlm/drlm.sqlite.save
	rm /etc/drlm/cert/drlm.*
	;;

    *)
        exit 0
        ;;
esac

exit 0
