'\" t
.\"     Title: drlm
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 04/01/2014
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "DRLM" "8" "04/01/2014" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
drlm \- Disaster Recovery Linux Manager
.SH "SYNOPSIS"
.sp
\fBdrlm\fR [\fB\-dDsSvV\fR] \fICOMMAND\fR [\-\- \fIARGS\fR\&...]
.SH "DESCRIPTION"
.sp
DRLM is the first central manager for ReaR, the leading Open Source disaster recovery solution\&.
.sp
DRLM comes with ABSOLUTELY NO WARRANTY; for details see the GNU General Public License at: \m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\&.html\fR\m[]
.SH "OPTIONS"
.SS "GLOBAL OPTIONS"
.PP
\-d
.RS 4

\fBdebug mode\fR
(log debug messages to log file)
.RE
.PP
\-D
.RS 4

\fBdebugscript mode\fR
(log every function call)
.RE
.PP
\-s
.RS 4

\fBsimulation mode\fR
(show what scripts drlm would include)
.RE
.PP
\-S
.RS 4

\fBstep\-by\-step mode\fR
(acknowledge each script individually)
.RE
.PP
\-v
.RS 4

\fBverbose mode\fR
(show progress output)
.RE
.PP
\-V
.RS 4
version information
.RE
.SS "COMMANDS"
.PP
\fBaddclient\fR
.RS 4
register new client to DB.
.RE
.PP
\fBaddjob\fR
.RS 4
register backup job to DB.
.RE
.PP
\fBaddnetwork\fR
.RS 4
register new network to DB.
.RE
.PP
\fBbkpmgr\fR
.RS 4
manage DRLM backup states.
.RE
.PP
\fBdelbackup\fR
.RS 4
delete backup and unregister from DB.
.RE
.PP
\fBdelclient\fR
.RS 4
delete client from DB.
.RE
.PP
\fBdeljob\fR
.RS 4
delete job from DB.
.RE
.PP
\fBdelnetwork\fR
.RS 4
delete network from DB.
.RE
.PP
\fBexpbackup\fR
.RS 4
export DR file.
.RE
.PP
\fBimpbackup\fR
.RS 4
import DR file.
.RE
.PP
\fBinstclient\fR
.RS 4
install client from DRLM
.RE
.PP
\fBlistbackup\fR
.RS 4
list client backups.
.RE
.PP
\fBlistclient\fR
.RS 4
list existent clients.
.RE
.PP
\fBlistjob\fR
.RS 4
list client jobs.
.RE
.PP
\fBlistnetwork\fR
.RS 4
list existent networks.
.RE
.PP
\fBmodclient\fR
.RS 4
 modify client properties.
.RE
.PP
\fBmodnetwork\fR
.RS 4
modify network properties.
.RE
.PP
\fBrunbackup\fR
.RS 4
modify network properties.
.RE
.PP
\fBsched\fR
.RS 4
manage job scheduler.
.sp
.SS "ARGUMENTS"
.PP
\-c \-\-client
.RS 4

\fBclient name\fR
(client_name, used in addclient, addnetwork, bkpmgr, addjob, deljob, listjob, delclient and impbackup arguments)
.RE
.PP
\-i \-\-ipaddr
.RS 4

\fBip address\fR
(ip address, used in addclient and addnetwork arguments)
.RE
.PP
\-M \-\-macaddr
.RS 4

\fBmac address\fR
(client mac address)
.RE
.PP
\-n \-\-netname
.RS 4

\fBnetwork name\fR
(this parameter must exists on the network database, used in addnetwork,addclient,delnetwork)
.RE
.PP
\-g \-\-gateway
.RS 4

\fBgateway\fR
(network argument)
.RE
.PP
\-m \-\-mask
.RS 4

\fBmask\fR
(network argument)
.RE
.PP
\-s \-\-server
.RS 4

\fBserver name\fR
(network argument)
.RE
.PP
\-I \-\-id
.RS 4

\fBbackup, client and network id's\fR
(bkpmgr, delclient, delbackup, delnetwork and expbackup argument)
.RE
.PP
\-J \-\-job_id
.RS 4

\fBjob id\fR
(deljob and listjob argument)
.RE
.PP
\-e \-\-enable
.RS 4

\fBenable backup or job scheduler\fR
(bkpmgr and sched argument)
.RE
.PP
\-d \-\-disable
.RS 4

\fBdisable backup or job scheduler\fR
(bkpmgr and sched argument)
.RE
.PP
\-r \-\-run
.RS 4

\fBrun planned jobs in scheduler\fR
(sched argument)
.RE
.PP
\-r \-\-repeat
.RS 4

\fBset periodicity of job\fR
(addjob argument in following format: 1min(s) or 1hour(s) or 1day(s) or 1week(s) or 1month(s) or 1year(s))
.RE
.PP
\-s \-\-start_date
.RS 4

\fBset start date for a new job\fR
(addjob argument in following format: %Y-%m-%dT%H:%M)
.RE
.PP
\-e \-\-end_date
.RS 4

\fBset end date for a new job\fR
(addjob argument in following format: %Y-%m-%dT%H:%M)
.RE
.PP
\-P
.RS 4

\fBpermanent backup\fR
(bkpmgr argument)
.RE
.PP
\-u \-\-user
.RS 4

\fBAdmin user\fR
(instclient argument)
.RE
.PP
\-f \-\-file
.RS 4

\fBdr file\fR
(expbackup and impbackup argument)
.RE
.PP
\-U \-\-url_rear
.RS 4

\fBURL ReaR\fR
(instclient argument)
.RE
.PP
\-A \-\-all
.RS 4

\fBAll\fR
(delbackup, listclient, listnetwork, listjob and listbackup argument)
.RE
.PP
\-h \-\-help
.RS 4

\fBhelp\fR
(show help)
.RE


.sp
Use \fIdrlm COMMAND \-\-help\fR for more advanced commands\&.
.SH "BACKGROUND INFORMATION"
.sp
The process of bare metal disaster recovery consists of two parts:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.RE
.SH "EXAMPLES"
.sp
The next examples shows how to use drlm from command line\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# drlm -dv listclient --all
.fi
.if n \{\
.RE
.\}
.sp
To list all clients in the database\&. Options debug and Verbose are applied.
.sp
.if n \{\
.RS 4
.\}
.nf
# drlm -vD addnetwork -i 192\&.168\&.2\&.0 -g 192\&.168\&.2\&.1 -s 192\&.168\&.2\&.10 -n Net1 -m 255\&.255\&.255\&.0
.fi
.if n \{\
.RE
.\}
.sp
To create a new network \&. Options debug and Verbose are applied.
.sp
.if n \{\
.RS 4
.\}
.nf
# drlm -vD addclient -n Net1 -i 192\&.168\&.2\&.113 -M 08\&:00\&:27\&:02\&:01\&:A7 -c WOPR
.fi
.if n \{\
.RE
.\}
.sp
To create a new client (WOPR) in this example\&. Options debug and Verbose are applied\&. Net1 must exist\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# drlm -vD instclient -u admin -c WOPR -U \m[blue]\fBhttp://download\&.opensuse\&.org/repositories/Archiving\&:/Backup\&:/Rear/Debian_8.0/all/rear_1\&.17\&.2_all\&.deb\fR\m[]
.fi
.if n \{\
.RE
.\}
.sp
To install ReaR and configure DRLM on a new client \&. Options debug and Verbose are applied.
.sp
.if n \{\
.RS 4
.\}
.nf
# drlm -vD addclient -n Net1 -i 192\&.168\&.2\&.113 -M 08\&:00\&:27\&:02\&:01\&:A7 -c WOPR -I -u admin -c WOPR -U \m[blue]\fBhttp://download\&.opensuse\&.org/repositories/Archiving\&:/Backup\&:/Rear/Debian_8.0/all/rear_1\&.17\&.2_all\&.deb\fR\m[]
.fi
.if n \{\
.RE
.\}
.sp
To create a new client (WOPR) and install/configure ReaR with an admin user in this example\&. Options debug and Verbose are appliedi\&. Net1 must exist\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# drlm -vD addjob -c reardeb8 -s 2017-01-03T22:50 -e 2018-01-03T23:55 -r 1month\fR\m[]
.fi
.if n \{\
.RE
.\}
.sp
To create a new monthly job for client reardeb8 starting at 2017-01-03T22:50 with end date 2018-01-03T23:55\&. Options debug and Verbose are applied\&. reardeb8 client must exist\&.
.sp

.SH "FILES"
.PP
/usr/sbin/drlm
.RS 4
The program itself\&.
.RE
.PP
/usr/share/drlm/conf/default.conf
.RS 4
Default configuration file\&. Contains a complete set of parameters and its explanation\&. Please do not edit or modify\&. Copy values to
\fIlocal\&.conf\fR
or
\fIsite\&.conf\fR
instead\&.
.RE
.PP
/etc/drlm/local\&.conf
.RS 4
System specific configuration can be set here\&.
.RE
.PP
/etc/drlm/site\&.conf
.RS 4
Site specific configuration can be set here\&.
.RE
.PP
/etc/cron\&.d/drlm
.RS 4
DRLM cron file\&.
.RE
.PP
/etc/bash_completion\&.d/drlm
.RS 4
DRLM bash-completion file\&.
.RE
.PP
/var/log/drlm/
.RS 4
Directory holding log files\&.
.RE
.PP
/etc/drlm/
.RS 4
Directory holding configuration files\&.
.RE
.PP
/etc/drlm/certs
.RS 4
Directory holding cert files\&.
.RE
.PP
/etc/drlm/clients
.RS 4
Directory holding client configuration files\&.
.RE
.PP
/tmp/drlm\&.####
.RS 4
DRLM script components\&.
.RE
.SH "BUGS"
.sp
Feedback is welcome, please report any issues or improvements to our issue\-tracker at: \m[blue]\fBhttp://github\&.com/brainupdaters/drlm/issues/\fR\m[]
.SH "AUTHORS"
.sp
Pau Roura, Didac Oliveira, Ruben Carbonell\&.
.sp
Logan & Krbu & Mad Max (this man page)\&.
.sp
DRLM is a collaborative process using Github at: \m[blue]\fBhttp://github\&.com/brainupdaters/drlm/\fR\m[]
.sp
The DRLM website is located at: \m[blue]\fBhttp://DRLM\&.org/\fR\m[]
.SH "COPYRIGHT"
.sp
(c) 2013\-2017
.sp
Pau Roura
.sp
Didac Oliveira
.sp
Ruben Carbonell
.sp
Disaster Recovery Linux Manager comes with ABSOLUTELY NO WARRANTY; for details see the GNU General Public License at \m[blue]\fBhttp://www\&.gnu\&.org/licenses/gpl\&.html\fR\m[]
