# file with help functions to implement.

function modclienthelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls modclient [OPTARGS]" "Change Client properties"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client to change by NAME"
	printf '%-25s %-45s\n' "-I|--id <CLI_ID>" "Select Client to change by ID"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-i|--ipaddr <IP>" "Set new IP address to client"
	printf '%-25s %-45s\n' "-M|--macaddr <MAC>" "Set new MAC address to client"
	printf '%-25s %-45s\n' "-n|--netname <NET>" "Assign new NETWORK to client"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls modclient -c|--client <cli_name> [ options ]\n"
	printf "	or\n"
	printf "drls modclient -I|--id <cli_id> [ options ]\n"
	printf "\n"
}

function addclienthelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls addclient [OPTARGS]" "Add Client to database"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client name to add"
	printf '%-25s %-45s\n' "-i|--ipaddr <IP>" "Client IP address"
	printf '%-25s %-45s\n' "-M|--macaddr <MAC>" "Client MAC address"
	printf '%-25s %-45s\n' "-n|--netname <NET>" "Client NETWORK"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls addclient -c|--client <cli_name> -i|--ipaddr <cli_IP> -M|--macaddr <cli_MAC> -n|--netname <net_name>\n"
	printf "\n"
}

function addnetworkhelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls addnetwork [OPTARGS]" "Add Network to database"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-n|--netname <NET_NAME>" "Select Network name to add"
	printf '%-25s %-45s\n' "-i|--ipaddr <IP>" "Network IP address"
	printf '%-25s %-45s\n' "-g|--gateway <GATEWAY>" "Network gateway address"
	printf '%-25s %-45s\n' "-m|--mask <MASK>" "Network mask"
	printf '%-25s %-45s\n' "-s|--server <SERVER>" "Network server address"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls addnetwork -n|--netname <net_name> -i|--ipaddr <net_IP> -g|--gateway <net_Gateway> -m|--mask <net_mask> -s|--server <net_server_ip>\n"
	printf "\n"
}

function bkpmgrhelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls bkpmgr [OPTARGS]" "Backup Manager"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client name to modify backup"
	printf '%-25s %-45s\n' "-I|--if <BKP_ID>" "Select Backup IP to modify"
	printf '%-25s %-45s\n' "-e|--ennable" "Enable Backup"
	printf '%-25s %-45s\n' "-d|--disable" "Disable Backup"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-P" "Set backup to persistent mode"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls bkmgr -d -c|--client <cli_name> [ options ]\n"
	printf "	or\n"
	printf "drls bkmgr -e -c|--client <cli_name> -I|--id <bkp_ID> [ options ]\n"
	printf "\n"
}

function delclienhelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls delclient [OPTARGS]" "Delete Client fom Database"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client to delete by NAME"
	printf '%-25s %-45s\n' "-I|--id <CLI_ID>" "Select Client to delete by ID"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls delclient -c|--client <cli_name>\n"
	printf "	or\n"
	printf "drls delclient -I|--ID <cli_ID>\n"
	printf "\n"
}

function delnetworkhelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls delnetwork [OPTARGS]" "Delete Network fom Database"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-n|--netname <NET_NAME>" "Select Network to delete by NAME"
	printf '%-25s %-45s\n' "-I|--id <NET_ID>" "Select Network to delete by ID"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls delnetwork -n|--netname <net_name>\n"
	printf "	or\n"
	printf "drls delnetwork -I|--ID <net_ID>\n"
	printf "\n"
}

function instclienthelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls instclient [OPTARGS]" "Install REAR to a remote client"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client to install REAR by name"
	printf '%-25s %-45s\n' "-I|--id <NET_ID>" "Select Client to intall REAR by ID"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-D|--distro <DISTRO>" "Force to distro name"
	printf '%-25s %-45s\n' "-R|--release <RELEASE>" "Force to release name"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls insclient -c|--client <cli_name>\n"
	printf "	or\n"
	printf "drls instlient -I|--id <cli_ID> [ options ]\n"
	printf "\n"
}

function listbackuphelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls listbackup [OPTARGS]" "List DRLS database backups"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client to list its backups"
	printf '%-25s %-45s\n' "-A|--all" "List all backups"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls listbackup -c|--client <cli_name>\n"
	printf "	or\n"
	printf "drls listbackup -A\n"
	printf "\n"
}

function listclienthelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls listclient [OPTARGS]" "List DRLS database clients"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-c|--client <CLI_NAME>" "Select Client to list"
	printf '%-25s %-45s\n' "-A|--all" "List all clients"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls listclient -c|--client <cli_name>\n"
	printf "	or\n"
	printf "drls listclient -A\n"
	printf "\n"
}

function listnetworkhelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls listnetwork [OPTARGS]" "List DRLS database networks"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-n|--netname <NET_NAME>" "Select Network to list"
	printf '%-25s %-45s\n' "-A|--all" "List all networks"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls listnetwork -n|--netname <net_name>\n"
	printf "	or\n"
	printf "drls listnetwork -A\n"
	printf "\n"
}

function modnetworkhelp() {
	printf "\n"
	printf "\n"
	printf "$(tput bold)Usage:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "drls modnetwork [OPTARGS]" "Change Network properties"
	printf "\n"
	printf "$(tput bold)Required Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-n|--netname <CLI_NAME>" "Select Network to change by NAME"
	printf '%-25s %-45s\n' "-I|--id <CLI_ID>" "Select Network to change by ID"
	printf "\n"
	printf "$(tput bold)Options:\n$(tput sgr0)"
	printf '%-25s %-45s\n' "-i|--ipaddr <IP>" "Set new IP address to network"
	printf '%-25s %-45s\n' "-g|--gateway <GATEWAY>" "Set new GATEWAY address to network"
	printf '%-25s %-45s\n' "-m|--mask <MASK>" "Assign new MASK to network"
	printf '%-25s %-45s\n' "-m|--server <SERVER>" "Assign new SERVER to network"
	printf '%-25s %-45s\n' "-h|--help" "Show this help"
	printf "\n"
	printf "$(tput bold)Example:\n$(tput sgr0)"
	printf "drls modnetwork -n|--netname <net_name> [ options ]\n"
	printf "	or\n"
	printf "drls modnetwork -I|--id <net_id> [ options ]\n"
	printf "\n"
}




